### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime_dl.deeplearning.lstm'

### ISSUE THREAD

**Issue by jmrichardson** [sktime/sktime-dl#61]
Hi,

**Describe the bug**
I installed sktime-dl dev branch on my windows server:

```
git clone --single-branch --branch dev https://github.com/sktime/sktime-dl.git
cd sktime-dl
pip install .
```
and getting this error:

```
from sktime_dl.deeplearning import CNNClassifier
  ...: 
2020-08-07 10:03:06.513815: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-07 10:03:06.514140: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-268c17ad5901>", line 18, in <module>
    from sktime_dl.deeplearning import CNNClassifier
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\sktime_dl\deeplearning\__init__.py", line 34, in <module>
    from sktime_dl.deeplearning.lstm._regressor import LSTMRegressor
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'sktime_dl.deeplearning.lstm'
```
**Versions**
```

Windows-10-10.0.18362-SP0
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.5
SciPy 1.4.1
sktime 0.4.1
sktime_dl 0.1.0
```
Thanks for your help

**Comment by jmrichardson** [comment]
Hi, I was able to get around it by uninstalling and then adding sktime_dl folder to my sys path:

```
sys.path.insert(0, 'D:\\Projects\\tipjar\\sktime-dl')
from sktime_dl.deeplearning import CNNClassifier
```

However, I am not sure why `pip install .` didn't work.

**Comment by mloning** [comment]
Hey @jmrichardson, thanks for reporting the bug. I believe there was a missing `__init__.py` file in the `sktime-dl/deeplearning/lstm` module, I've added it on dev (commit: https://github.com/sktime/sktime-dl/commit/c72b23be9fd29fe0032c6cc8f3733be09ed4e3aa), I hope that solves the issue for you!

**Comment by jmrichardson** [comment]
Thank you and works great now! 👍

**Comment by talhaanwarch** [comment]
I am getting this error
`ModuleNotFoundError: No module named 'sktime.utils.data_container'
`while installing it on colab
```
!git clone https://github.com/sktime/sktime-dl.git
cd '/content/sktime-dl/'
!git checkout dev
!git pull origin dev
!pip install .
```
